# Generated by Django 2.2.6 on 2019-11-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191105_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_end_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_start_date',
            field=models.CharField(max_length=10),
        ),
    ]
