# Generated by Django 2.2.6 on 2019-11-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191105_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_start_date',
            field=models.DateField(),
        ),
    ]
