# Generated by Django 2.2.6 on 2019-11-17 18:40

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [0.0], 'marker_color': 'blue', 'style': 'mapbox://styles/mapbox/outdoors-v11'}),
        ),
        migrations.AlterField(
            model_name='ride',
            name='origin',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [23.755631229995345, 90.44724814154182], 'marker_color': 'blue', 'navigation_buttons': True, 'track_location_button': True}),
        ),
    ]
