# Generated by Django 2.2.6 on 2019-11-17 18:52

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191118_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=mapbox_location_field.models.AddressAutoHiddenField(),
        ),
    ]
