# Generated by Django 2.2.6 on 2019-11-17 18:54

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191118_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='origin',
            field=mapbox_location_field.models.AddressAutoHiddenField(),
        ),
    ]
